var cells = [
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name:  , position: 0, price: 0, rent: 0, group: },
	{name: "Kentucky Ave.", position: 21, price: 220, rent: 18, group: "Red"},
	{name: "Chance" , position: 22, price: 0, rent: 0, group: "Chance"},
	{name: "Indiana Ave.", position: 23, price: 220, rent: 18, group: "Red"},
	{name: "Illinois Ave.", position: 24, price: 240, rent: 20, group: "Red"},
	{name: "B. & O. Railroad", position: 25, price: 150, rent: 25, group: "Railroad"},
	{name: "Atlantic Ave.", position: 26, price: 260, rent: 22, group:"Yellow"},
	{name: "Ventnor Ave.", position: 27, price: 260, rent: 22, group:"Yellow"},
	{name: "Water Works", position: 28, price: 150, rent: 20, group:"Utility"},
	{name: "Marvin Gardens", position: 29, price: 280, rent: 22, group:"Yellow"},
	{name: "Go to Jail", position: 30, price: 0, rent: 0, group: "GoToJail"},
	{name: "Pacific Ave.", position: 31, price: 300, rent: 26, group: "Dark-Green" },
	{name: "North Carolina Ave.", position: 32, price: 300, rent: 26, group:"Dark-Green"},
	{name: "Community Chest", position: 33, price: 0, rent: 0, group:"Chest"},
	{name: "Pennsylvania Ave.", position: 34, price: 320, rent: 28, group:"Dark-Green"},
	{name: "Short Line Railroad", position: 35, price: 150, rent: 25, group:"Railroad"},
	{name: "Chance", position: 36, price: 0, rent: 0, group:"Chance"},
	{name: "Park Place", position: 37, price: 350, rent: 35, group: "Blue"},
	{name:  "Luxury Tax", position: 38, price: 0, rent: 0, group:"Tax"},
	{name: "Boardwalk", position: 39, price: 400, rent: 50, group:"Blue"},
	];
